#!/bin/bash

WDIR=${PWD}

cd ..
if [ -z ${ARMA_INCLUDE_PATH+x} ]; then 
    export ARMA_INCLUDE_PATH="$PWD/include"
fi
export CXXCOV=gcov
export LD_LIBRARY_PATH="$PWD:$PWD/glpk_tmp/lib":$LD_LIBRARY_PATH
cd tests

#

declare -a DIRS=("ancillary" "arums" "markets" "models" "solvers")

for i in "${DIRS[@]}"; do
    cd "$WDIR"/"$i"

    ./configure -c
    make -j
    sh ./../test_setup/cov_check
done

declare -a UNIT_DIRS=("unit_tests/arums" "unit_tests/misc" "unit_tests/mmfs" \
                      "unit_tests/models" "unit_tests/solvers" "unit_tests/transfers")

for i in "${UNIT_DIRS[@]}"; do
    cd "$WDIR"/"$i"

    ./configure -c
    make
    sh ./../../test_setup/cov_check
done
